name: flutter_favorite_calc
description: experimental calculators for determining flutter favorites scores.
version: 0.0.1
author: Ray Rischpater, KF6GPE <rischpater@google.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: ^1.5.0
  quiver: '>=2.0.0 < 3.0.0'
  glob: ^1.0.3
  path:
  lcov:
  github: ^5.0.0
  graphql: ^2.0.0

dev_dependencies:
  test: ^1.0.0
  pedantic:
